/** Toutes les pages du site Google Sites d'origine (lmtechno25). */
"use strict";

const BASE = "https://sites.google.com/view/lmtechno25";

const PATHS = [
  "home",
  "sicit",
  // ----- 5ème 2025-2026 -----
  "5ème-2025-2026",
  "5ème-2025-2026/séquence-1-cybersécurité-2025-2026",
  "5ème-2025-2026/séquence-1-cybersécurité-2025-2026/séance-1-exploiter-les-outils-numériques-et-en-faire-bon-usage",
  "5ème-2025-2026/séquence-1-cybersécurité-2025-2026/séance-1corr-exploiter-les-outils-numériques-et-en-faire-bon-usage",
  "5ème-2025-2026/séquence-1-cybersécurité-2025-2026/séance-2-se-protéger-et-protéger-ses-données",
  "5ème-2025-2026/séquence-1-cybersécurité-2025-2026/séance-2corr-se-protéger-et-protéger-ses-données",
  "5ème-2025-2026/séquence-1-cybersécurité-2025-2026/séance-3-agir-face-à-la-cyberviolence",
  "5ème-2025-2026/séquence-1-cybersécurité-2025-2026/séance-3corr-agir-face-à-la-cyberviolence",
  "5ème-2025-2026/séquence-1-cybersécurité-2025-2026/séance-4-organiser-un-espace-de-stockage",
  "5ème-2025-2026/séquence-1-cybersécurité-2025-2026/séance-4corr-organiser-un-espace-de-stockage",
  "5ème-2025-2026/séquence-1-cybersécurité-2025-2026/ressources",
  // ----- 4ème 2025-2026 -----
  "4ème-2025-2026",
  "4ème-2025-2026/séquence-0lia-générative-comme-assistant-personnel",
  "4ème-2025-2026/séquence-0lia-générative-comme-assistant-personnel/séance-1utiliser-lia-générative-comme-assistant-personnel",
  "4ème-2025-2026/séquence-0lia-générative-comme-assistant-personnel/séance-1corrutiliser-lia-générative-comme-assistant-personnel",
  "4ème-2025-2026/séquence-0lia-générative-comme-assistant-personnel/créer-un-prompt-efficace",
  "4ème-2025-2026/séquence-0lia-générative-comme-assistant-personnel/prompts-avantages-et-biais",
  "4ème-2025-2026/séquence-1-intelligence-artificielle-générative-la-sécurité-des-données",
  "4ème-2025-2026/séquence-1-intelligence-artificielle-générative-la-sécurité-des-données/séance-1une-maison-connectée-mais-à-quel-prix",
  "4ème-2025-2026/séquence-1-intelligence-artificielle-générative-la-sécurité-des-données/séance-1corrune-maison-connectée-mais-à-quel-prix",
  "4ème-2025-2026/séquence-1-intelligence-artificielle-générative-la-sécurité-des-données/séance-2le-numérique-au-quotidien-savoir-lutiliser-sans-danger",
  "4ème-2025-2026/séquence-1-intelligence-artificielle-générative-la-sécurité-des-données/séance-2-corrle-numérique-au-quotidien-savoir-lutiliser-sans-danger",
  "4ème-2025-2026/séquence-1-intelligence-artificielle-générative-la-sécurité-des-données/ressources",
  // ----- 5ème archives -----
  "5ème",
  "5ème/séquence-1-préserver-les-ressources",
  "5ème/séquence-1-préserver-les-ressources/séance-1-que-deviennent-nos-déchets",
  "5ème/séquence-1-préserver-les-ressources/séance-2-aider-les-usagers-à-éviter-les-erreurs-de-tri",
  "5ème/séquence-1-préserver-les-ressources/séance-3-créer-une-application-smartphone",
  "5ème/séquence-2-éclairage-automatique",
  "5ème/séquence-2-éclairage-automatique/séance-1-quest-ce-quun-système-automatique",
  "5ème/séquence-2-éclairage-automatique/séance-2-cahier-des-charges",
  "5ème/séquence-2-éclairage-automatique/séance-3-comment-est-constitué-un-système-automatique",
  "5ème/séquence-2-éclairage-automatique/séance-3-comment-est-constitué-un-système-automatique/synthèse-capteur-actionneur-interface",
  "5ème/séquence-2-éclairage-automatique/séance-3-comment-est-constitué-un-système-automatique/synthèse-systèmes-embarqués",
  "5ème/séquence-2-éclairage-automatique/séance-4la-programmation-dun-système-automatique",
  "5ème/séquence-3-vivre-dans-une-boite",
  "5ème/séquence-3-vivre-dans-une-boite/séance-1-problématique",
  "5ème/séquence-3-vivre-dans-une-boite/cahier-des-charges",
  "5ème/séquence-3-vivre-dans-une-boite/séance-3-fonctions-et-solutions-techniques",
  "5ème/séquence-3-vivre-dans-une-boite/séance-4-solutions-techiques",
  "5ème/séquence-3-vivre-dans-une-boite/séance-4-solutions-techiques/synthèse",
  "5ème/séquence-3-vivre-dans-une-boite/séance-5isoler-du-bruit",
  "5ème/séquence-3-vivre-dans-une-boite/séance-5isoler-du-bruit/fiches-de-connaissance",
  "5ème/séquence-3-vivre-dans-une-boite/séance-6-la-modélisation-du-conteneur",
  "5ème/séquence-3-vivre-dans-une-boite/séance-7-modéliser-lagencement-extérieur",
  "5ème/séquence-4-animal-sounds-for-kids",
  "5ème/eval-assr1",
  "5ème/eval-assr1/assr1",
  "5ème/eval-assr1/5ème-a",
  "5ème/eval-assr1/5ème-b",
  "5ème/eval-assr1/5ème-c",
  // ----- 4ème archives -----
  "4ème",
  "4ème/séquence-1-le-réseau-informatique",
  "4ème/séquence-1-le-réseau-informatique/séance-1-réseau-du-collège",
  "4ème/séquence-1-le-réseau-informatique/séance-2-situation-problème",
  "4ème/séquence-1-le-réseau-informatique/séance-3-solution-ipwebcam",
  "4ème/séquence-1-le-réseau-informatique/séance-4-adresse-ip",
  "4ème/séquence-2-portail-automatisé",
  "4ème/séquence-2-portail-automatisé/séance-0-situation-déclenchante",
  "4ème/séquence-2-portail-automatisé/séance-1-etude-du-besoin",
  "4ème/séquence-2-portail-automatisé/séance-1-etude-du-besoin/correction-séance-1",
  "4ème/séquence-2-portail-automatisé/séance-2-les-contraintes",
  "4ème/séquence-3-les-objets-connectés",
  "4ème/séquence-3-les-objets-connectés/séance1-les-objets-connectés",
  "4ème/séquence-3-les-objets-connectés/séance-2-comment-piloter-un-objet-technique-avec-un-smartphone",
  "4ème/séquence-4-programmer-un-ordinateur-de-poche",
  "4ème/séquence-4-programmer-un-ordinateur-de-poche/séance-1-la-carte-microbit",
  "4ème/séquence-4-programmer-un-ordinateur-de-poche/séance-2-activitésles-défis-microbit",
  "4ème/séquence-4-programmer-un-ordinateur-de-poche/séance-2-activitésles-défis-microbit/correction",
  "4ème/séquence-4-programmer-un-ordinateur-de-poche/programmer-une-boussolle",
  "4ème/séquence-5-comment-simuler-le-fonctionnement-dun-feu-tricolore-arduino",
  "4ème/séquence-5-comment-simuler-le-fonctionnement-dun-feu-tricolore-arduino/séance-1-observer-et-décrire-la-structure-dun-objet",
  "4ème/séquence-5-comment-simuler-le-fonctionnement-dun-feu-tricolore-arduino/séance-2-algorithme-et-programmation",
  "4ème/séquence-6-serre-autonome",
  "4ème/séquence-6-serre-autonome/séance-0-présentation-du-projet",
  "4ème/séquence-6-serre-autonome/séance-1-analyse-fonctionnelle",
  "4ème/séquence-6-serre-autonome/séance-2-modélisation-3d-de-la-serre",
  "4ème/séquence-6-serre-autonome/séance-3-programmer-un-système",
  "4ème/chaines-fonctionnelles",
  "4ème/chaines-fonctionnelles/exercices",
  "4ème/chaines-fonctionnelles/correction",
  "4ème/olympiades-informatique",
  // ----- 3ème archives -----
  "3ème",
  "3ème/séquence-1-la-poubelle-connectée",
  "3ème/séquence-1-la-poubelle-connectée/séance-1-comment-décrire-le-fonctionnement",
  "3ème/séquence-1-la-poubelle-connectée/correction",
  "3ème/séquence-1-la-poubelle-connectée/modélisation-3d-de-la-poubelle",
  "3ème/séquence-1-la-poubelle-connectée/prototype-arduino",
  "3ème/séquence-1-la-poubelle-connectée/simulation-tinkercad",
  "3ème/séquence-2-intelligence-artificielle",
  "3ème/séquence-2-intelligence-artificielle/séance-1-cest-quoi-lintelligence-artificielle",
  "3ème/séquence-2-intelligence-artificielle/séance-2",
  "3ème/séquence-2-intelligence-artificielle/tuto-vidéos-teachable-maching",
  "3ème/séquence-2-intelligence-artificielle/séance-3",
  "3ème/séquence-2-intelligence-artificielle/séance-4-zonde-de-programmation",
  "3ème/séquence-2-intelligence-artificielle/fiche-de-connaissance",
  "3ème/séquence-3-réseau-informatique",
  "3ème/séquence-3-réseau-informatique/séance-1",
  "3ème/séquence-3-réseau-informatique/séance-2",
  "3ème/séquence-3-réseau-informatique/séance-3",
  "3ème/séquence-3-réseau-informatique/tp",
  "3ème/assr2-pix",
  "3ème/assr2-pix/3ème-a",
  "3ème/assr2-pix/3ème-b",
  "3ème/sessions-dnb",
  "3ème/chaines-fonctionnelles",
  "3ème/fonctions-techniques-solutions-techniques",
  // ----- 2nde SNT -----
  "2nde-snt",
  "2nde-snt/thème-2-internet",
  "2nde-snt/thème-2-internet/tcpip",
  "2nde-snt/thème-2-internet/tcpip/fiche-de-révision",
  "2nde-snt/thème-2-internet/routage",
  "2nde-snt/thème-2-internet/routage/exercices",
  "2nde-snt/thème-2-internet/routage/synthèse",
  "2nde-snt/thème-2-internet/dns-et-réseaux-pair-à-pair",
  "2nde-snt/thème-2-internet/support-du-cours",
  "2nde-snt/thème-3-web",
  "2nde-snt/thème-3-web/1-histoire-du-web",
  "2nde-snt/thème-3-web/2-fonctionnement-du-web",
  "2nde-snt/thème-3-web/3-lécriture-dune-page-web",
  "2nde-snt/thème-3-web/4-le-langage-htmlcss-2",
  "2nde-snt/tp-arduino",
  "2nde-snt/thème-4-photographie-numérique",
  "2nde-snt/thème-4-photographie-numérique/parite-1-loeil-et-le-capteur-numérique",
  "2nde-snt/thème-4-photographie-numérique/partie-2-formats-des-images",
  "2nde-snt/thème-5-géolocalisation",
  "2nde-snt/thème-5-géolocalisation/séance-1-les-bases-de-la-cartographie",
  "2nde-snt/thème-5-géolocalisation/la-géolocalisation-par-satellite",
  "2nde-snt/thème-5-géolocalisation/le-protocole-nmea",
];

/** Clé de fichier déterministe et ASCII pour un chemin de page. */
function keyOf(p) {
  return p
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-zA-Z0-9/]+/g, "-")
    .replace(/\//g, "__")
    .replace(/-+/g, "-")
    .toLowerCase();
}

module.exports = { BASE, PATHS, keyOf };
